#! /bin/bash

$HOME/.config/polybar/launch
pgrep -x sxhkd > /dev/null || sxhkd &

nitrogen --restore &

bspc monitor LVDS1 -d 1 2 3

if [[ $(xrandr -q | grep -io "vga1 connected") ]]; then
    xrandr --output LVDS1 --primary --mode 1024x600 --rotate normal --rate 60.00 --output VGA1 --mode 1024x768 --rotate normal --rate 60.00 --right-of LVDS1

    bspc monitor VGA1 -d 4
fi

bspc config border_width         2
bspc config window_gap          12

bspc config normal_border_color  "#252525"
bspc config focused_border_color  "#6fe300"
bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a firefox-esr desktop='^2' state=floating follow=on
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
