#!/bin/bash

_dir=storage/music
carga (){
    rclone copy --transfers 1 -P $_dir $1
}

if [[ $(ls $_dir | wc -l) -gt 1 ]]; then
    case $1 in
        rc) carga flac:dir2;;
        ch) carga dropbox:musica/chida;;
        ro) carga pcloud:musica/romanticas;;
        *) echo "Error";;
    esac
    if [[ ! $? -eq 0 ]]; then
        _message="Music is failed!"
        _tags=warning,skull
    fi
else
    echo "Nada que hacer."
    exit 0
fi

curl \
    -H "Title: Rclone music" \
    -H "Priority: urgent" \
    -d "${_message:-"Music is done!"}" \
    -H "Tags: ${_tags:-"iphone,white_check_mark"}" \
    ntfy.sh/${API_NTFY} > /dev/null 2>&1
