#!/bin/bash

_dir=/sdcard/Music

if [[ $(ls -A $_dir) ]]; then
    rclone copy -P --transfers 1 $_dir mega:flac
    if [[ ! $? -eq 0 ]]; then
        _title="Title: Rclone music rock"
        _message="Mega music is fail!!!"
    fi
else
    echo "Nada que hacer."
    exit 0
fi

curl \
    -H "$_title" \
    -H "Priority: urgent" \
    -d "${_message:-"Mega music is done!!!"}" \
    ntfy.sh/$API_NTFY &> /dev/null
