#!/bin/bash

#set -x

_boost=$(ls /sdcard/Pictures/Boost | wc -l)
_fil=$(cat boost.txt)

if [[ $_boost -gt $_fil ]]; then
    rclone copy -P /sdcard/Pictures/Boost megap:pics/reddit && ls /sdcard/Pictures/Boost | wc -l > boost.txt
    if [[ ! $? -eq 0 ]]; then
        _title="Title: Reddit Local"
        _message="Rclone backup fail!"
    fi
else
    echo "Nada que hacer."
    exit 0
fi

curl \
    -H "$_title" \
    -H "Priority: urgent" \
    -d "${_message:-"Rclone backup done!"}" \
    ntfy.sh/$API_NTFY &> /dev/null
