#!/bin/bash

#set -x

_boost=$(ls storage/pictures/boost | wc -l)
_fil=$(cat boost.txt)

if [[ $_boost -gt $_fil ]]; then
    rclone copy -P /sdcard/Pictures/Boost dropbox:pics/reddit && ls /sdcard/Pictures/Boost | wc -l > boost.txt
    if [[ ! $? -eq 0 ]]; then
        _message="Rclone backup is failed!"
        _tags=warning,skull
    fi
else
    echo "Nada que hacer."
    exit 0
fi

curl \
    -H "Title: Reddit local" \
    -H "Priority: urgent" \
    -d "${_message:-"Rclone backup done!"}" \
    -H "Tags: ${_tags:-"iphone,white_check_mark"}" \
    ntfy.sh/${API_NTFY} &> /dev/null
