#!/bin/bash

mrock=$(rclone lsf mega:flac | wc -l)
lrock=$(ls ~/Música/javier/rock-flac | wc -l)

if [[ $mrock -gt $lrock ]]; then
    notify-send -t 5000 "Rock music is updating..."
    curl \
        -H "Title: Update music in $(uname -sn)" \
        -H "Priority: urgent" \
        -d "Rock is updating..." \
        ntfy.sh/XlainRoot93 &> /dev/null
    proc=$(rclone sync -P mega:flac/ ~/Música/javier/rock-flac)
    if [[ $? -eq 0 ]]; then
        notify-send -t 5000 "Rock Music" "$(( $mrock-$lrock )) New song(s)!"
        title="Rock sync in $(uname -sn)"
        message="$(( $mrock-$lrock )) New song(s)!"
    else
        notify-send -t 5000 "Rock Music" "Algo salió mal!"
        title="Rock sync in $(uname -sn)"
        message="Algo salió mal! $proc"
    fi
else
    notify-send -t 5000 "Rock sync" "Rock is ok!"
    exit 0
fi

curl \
    -H "Title: $title" \
    -H "Priority: urgent" \
    -d "$message" \
    ntfy.sh/XlainRoot93 &> /dev/null
