#!/bin/bash

# rock
mrock=$(rclone lsf pcloud:musica/romanticas | wc -l)
lrock=$(ls ~/Música/javier/romanticas | wc -l)

if [[ $mrock -gt $lrock ]]; then
    notify-send -t 5000 "Romanticas music is updating..."
    curl \
        -H "Title: Update music in $(uname -sn)" \
        -H "Priority: urgent" \
        -d "Romanticas is updating..." \
        ntfy.sh/change_url &> /dev/null
    proc=$(rclone sync -P pcloud:musica/romanticas ~/Música/javier/romanticas)
    if [[ $? -eq 0 ]]; then
        notify-send -t 5000 "Romanticas Music" "$(($mrock-$lrock)) New song(s)!"
        title="Romanticas sync in $(uname -sn)"
        message="$(($mrock-$lrock)) New song(s)!"
    else
        notify-send -t 5000 "Romanticas Music" "Algo salió mal!"
        title="Romanticas sync in $(uname -sn)"
        message="Algo salió mal! $proc"
    fi
else
    notify-send -t 5000 "Romanticas sync" "Romanticas is ok!"
    exit 0
fi

curl \
    -H "Title: $title" \
    -H "Priority: urgent" \
    -d "$message" \
    ntfy.sh/change_url &> /dev/null
